name: Generate

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dst repo
        uses: actions/checkout@master
        with:
          repository: ciur/dst-repo
          path: temp-dst-repo
          ref: main

      - name: Checkout current repo
        uses: actions/checkout@master
        with:
          path: current-repo
          ref: main

      - name: Generate File
        run: |
          cat temp-dst-repo/date.txt
          cat temp-dst-repo/date.txt > current-repo/upstream_version.txt

      - name: Echo created file
        run: |
            cat current-repo/upstream_version.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          add-paths: |
            upstream_version.txt
          path: current-repo
          labels: automerge

      - name: Merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 60
          labels: automerge
          repository: ciur/3rd-repo
          pullRequestNumber:  ${{ steps.cpr.outputs.pull-request-number }}
          token: ${{ secrets.GH_PAT_TOKEN }}
          checkStatus: false
